-- ==============================================================================
-- Supabase PostgreSQL Schema for Retoucher CRM
-- Copy & paste into Supabase SQL Editor and click RUN
-- ==============================================================================

-- 1. contacts
CREATE TABLE IF NOT EXISTS contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_name TEXT NOT NULL,
    country TEXT,
    website TEXT,
    instagram TEXT,
    email TEXT,
    email_status TEXT DEFAULT 'unverified',
    decision_maker TEXT,
    language TEXT DEFAULT 'en',
    category TEXT,
    priority TEXT DEFAULT 'medium',
    catalog_size TEXT,
    photo_quality TEXT,
    cultural_profile TEXT DEFAULT 'standard',
    timezone_note TEXT,
    source_base TEXT,
    pipeline_status TEXT DEFAULT 'lead',
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. touches
CREATE TABLE IF NOT EXISTS touches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    channel TEXT,
    template_type TEXT,
    subject TEXT,
    sent_date DATE,
    status TEXT DEFAULT 'sent',
    next_action_date DATE,
    notes TEXT
);

-- 3. deals
CREATE TABLE IF NOT EXISTS deals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    deal_type TEXT DEFAULT 'one-off',
    description TEXT,
    amount_usd NUMERIC(12, 2) DEFAULT 0.0,
    payment_method TEXT,
    upwork_contract_url TEXT,
    status TEXT DEFAULT 'in_progress',
    created_date DATE,
    delivered_date DATE,
    paid_date DATE
);

-- 4. payments
CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deal_id BIGINT NOT NULL REFERENCES deals(id) ON DELETE CASCADE,
    gross_usd NUMERIC(12, 2) DEFAULT 0.0,
    platform_fee_percent NUMERIC(5, 2) DEFAULT 0.0,
    platform_fee_usd NUMERIC(12, 2) DEFAULT 0.0,
    withdrawal_fee NUMERIC(12, 2) DEFAULT 0.0,
    net_usd NUMERIC(12, 2) DEFAULT 0.0,
    usd_uah_rate NUMERIC(8, 2) DEFAULT 0.0,
    net_uah NUMERIC(12, 2) DEFAULT 0.0,
    tax_rate NUMERIC(5, 4) DEFAULT 0.1950,
    tax_reserved_uah NUMERIC(12, 2) DEFAULT 0.0,
    date_received DATE,
    date_withdrawn DATE,
    declaration_month TEXT
);

-- 5. retainers
CREATE TABLE IF NOT EXISTS retainers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    monthly_amount_usd NUMERIC(12, 2) DEFAULT 0.0,
    images_per_month INTEGER DEFAULT 0,
    start_month TEXT,
    status TEXT DEFAULT 'active',
    next_contract_ping_date DATE,
    notes TEXT
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_contacts_pipeline ON contacts(pipeline_status);
CREATE INDEX IF NOT EXISTS idx_touches_next_action ON touches(next_action_date);
CREATE INDEX IF NOT EXISTS idx_touches_contact ON touches(contact_id);
CREATE INDEX IF NOT EXISTS idx_deals_contact ON deals(contact_id);
CREATE INDEX IF NOT EXISTS idx_retainers_ping ON retainers(next_contract_ping_date);

-- Demo Seed Data (if empty)
INSERT INTO contacts (
    brand_name, country, website, instagram, email, email_status,
    decision_maker, language, category, priority, catalog_size,
    photo_quality, cultural_profile, timezone_note, source_base,
    pipeline_status, notes
) VALUES
('Lumina Fine Jewels', 'US', 'https://luminajewels.com', '@luminajewels', 'sarah@luminajewels.com', 'valid', 'Sarah Jenkins (Creative Director)', 'en', 'Fine Jewelry', 'high', '250 items', 'Mid (needs metal smoothing and diamond brilliance)', 'aggressive', 'EST (UTC-5)', 'Instagram Outreach', 'contacted', 'Interested in clean white background and editorial renders.'),
('Aethelgard Silver', 'GB', 'https://aethelgard.co.uk', '@aethelgard_uk', 'edward@aethelgard.co.uk', 'valid', 'Edward Vance (Founder)', 'en', 'Silver & Gothic', 'medium', '80 items', 'Raw studio photos with heavy shadows', 'standard', 'GMT (UTC+0)', 'Google Search', 'lead', 'Handcrafted rings, focus on texture preservation.'),
('Milano Oro & Pietre', 'IT', 'https://milanooro.it', '@milano_oro', 'marco.rossi@milanooro.it', 'unverified', 'Marco Rossi (Owner)', 'en', 'High Jewelry', 'high', '120 items', 'Good camera, mediocre post-production', 'patient', 'CET (UTC+1)', 'VicenzaOro Exhibitor List', 'replied', 'Requested before/after samples of emeralds and gold reflections.'),
('Atelier Dauphin Paris', 'FR', 'https://atelier-dauphin.fr', '@atelierdauphin', 'claire@atelier-dauphin.fr', 'valid', 'Claire Laurent (Marketing Lead)', 'fr', 'Contemporary Art Jewelry', 'medium', '150 items', 'High quality 3D CAD renders needing photorealism touch', 'slow', 'CET (UTC+1)', 'LinkedIn', 'negotiation', 'Currently discussing test batch of 15 pieces.'),
('Nordic Aurum Studio', 'SE', 'https://nordicaurum.se', '@nordic.aurum', 'astrid@nordicaurum.se', 'unverified', 'Astrid Lind (Designer)', 'en', 'Minimalist Jewelry', 'low', '45 items', 'iPhone daylight photos', 'patient', 'CET (UTC+1)', 'Instagram', 'lead', 'Small collection, might need budget package.')
ON CONFLICT DO NOTHING;

INSERT INTO touches (contact_id, channel, template_type, subject, sent_date, status, next_action_date, notes) VALUES
(1, 'Email', 'initial_cold', 'Quick retouching question for Lumina Fine Jewels', '2026-09-10', 'sent', '2026-09-13', 'Cold email with link to curated diamond ring portfolio.'),
(3, 'Instagram', 'dm_compliment', 'Compliment on emerald collection & test offer', '2026-09-08', 'replied', '2026-09-15', 'Client replied asking for pricing per item.'),
(4, 'Email', 'portfolio_followup', 'Test piece estimation for Atelier Dauphin Paris', '2026-09-05', 'sent', '2026-09-15', 'Sent quote of $750 for 15 pieces. Waiting for approval.')
ON CONFLICT DO NOTHING;

INSERT INTO deals (contact_id, deal_type, description, amount_usd, payment_method, upwork_contract_url, status, created_date, delivered_date, paid_date) VALUES
(4, 'one-off', 'Test batch: 15 pieces lookbook retouching', 750.00, 'Upwork', 'https://www.upwork.com/contracts/~01testdauphin123', 'in_progress', '2026-09-11', '2026-09-18', NULL)
ON CONFLICT DO NOTHING;
